index:
#building
	gcc -c pilhas.c -g
	gcc -c filas.c -g
	gcc -c graph.c -g
	gcc -c heap.c -g
	gcc -c cdisj.c -g
	gcc -c main.c -g
	gcc -o graf main.o graph.o pilhas.o filas.o heap.o cdisj.o -g

clear:
#cleaning
	rm bib.o
	rm exe